apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:

  tasks:
    - name: task1
      taskRef:
        name: print-message1
      runAfter:
      - task2
      params:
      - name: message
        value: "Hello Openshift Pipeline-1"    
    - name: task2
      taskRef:
        name: print-message2
      params:
      - name: message
        value: "Hello Openshift Pipeline-2"    

