apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:

  workspaces:
    - name: shared-workspace

  params:
    - name: git-url
      type: string

  tasks:

    - name: clone-source

      taskRef:
        name: git-clone

      params:
        - name: url
          value: $(params.git-url)

      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-image

      runAfter:
        - clone-source

      taskRef:
        name: buildah

      params:
        - name: IMAGE
          value: default-route-openshift-image-registry.apps.ocp4.example.com/test100/test1

      workspaces:
        - name: source
          workspace: shared-workspace
